package com.ejudge.clion

import java.nio.file.Files
import java.nio.file.Path

/** Generates CMake files so CLion can index solutions that live outside the user's own project. */
object CMakeGen {
    private val HEADERS = listOf(
        "algorithm", "array", "bitset", "cassert", "cctype", "chrono", "climits", "cmath", "complex", "cstdint",
        "cstdio", "cstdlib", "cstring", "ctime", "deque", "functional", "iomanip", "iostream", "iterator",
        "limits", "list", "map", "memory", "numeric", "queue", "random", "set", "sstream", "stack", "string",
        "tuple", "unordered_map", "unordered_set", "utility", "vector",
    )

    /** Text of a replacement for <bits/stdc++.h>, which macOS toolchains lack. */
    val STDCPP_SHIM: String = HEADERS.joinToString("\n") { "#include <$it>" } + "\n"

    fun generate(root: Path) {
        if (!Files.isDirectory(root)) return
        Files.createDirectories(root.resolve(".include/bits"))
        Files.writeString(root.resolve(".include/bits/stdc++.h"), STDCPP_SHIM)
        val contests = Files.list(root).use { s ->
            s.filter { Files.isDirectory(it) && !it.fileName.toString().startsWith(".") }.sorted().toList()
        }
        val included = mutableListOf<String>()
        for (contest in contests) {
            val problems = Files.list(contest).use { s -> s.filter { Files.exists(it.resolve(MARKER)) }.sorted().toList() }
            if (problems.isEmpty()) continue
            val id = Files.readAllLines(problems[0].resolve(MARKER)).getOrNull(2) ?: "0"
            val sb = StringBuilder("# Generated by the Ejudge plugin\ninclude_directories(\${CMAKE_CURRENT_SOURCE_DIR}/../.include)\n")
            for (p in problems) {
                val src = TestRunner.sourceOf(p) ?: continue
                if (src.fileName.toString().substringAfterLast('.') !in setOf("cpp", "cc", "cxx")) continue
                val letter = Files.readAllLines(p.resolve(MARKER)).getOrNull(1) ?: p.fileName.toString()
                val tag = "c${id}_${letter.replace(Regex("[^A-Za-z0-9_]"), "_")}"
                sb.append("add_executable($tag \"${p.fileName}/${src.fileName}\")\n")
            }
            Files.writeString(contest.resolve("CMakeLists.txt"), sb.toString())
            included += contest.fileName.toString()
        }
        val rootText = StringBuilder(
            "# Generated by the Ejudge plugin\ncmake_minimum_required(VERSION 3.20)\nproject(ejudge_contests CXX)\n" +
                "set(CMAKE_CXX_STANDARD 17)\nset(CMAKE_CXX_STANDARD_REQUIRED ON)\n"
        )
        included.forEach { rootText.append("add_subdirectory(\"$it\")\n") }
        Files.writeString(root.resolve("CMakeLists.txt"), rootText.toString())
    }
}
